import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// import type { Metadata } from 'next';
// import "../styles/globals.css";
// import { Providers } from "./providers";
// import {
//   getLangFromCookies,
//   LANG_MAP,
//   DEFAULT_LANG,
//   SupportedLang,
//   Translations,
// } from "@/libs/i18n-core";

// import { TranslationProvider } from "@/contexts/TranslationContext";

// export const metadata: Metadata = {
//   title: 'Team Solutions Viet Nam',
//   description: 'Team Solutions Viet Nam',
// }

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const lang: SupportedLang = await getLangFromCookies();
//   const translations = (LANG_MAP[lang] ?? LANG_MAP[DEFAULT_LANG]) as Translations;
//   return (
//     <html lang={lang} suppressHydrationWarning>
//       <body>
//         <div className="bg-white flex flex-col min-w-[1850px]">
//           <TranslationProvider lang={lang} translations={translations}>
//             <Providers>
//               {children}
//             </Providers>
//           </TranslationProvider>
//         </div>
//       </body>
//     </html>
//   );
// }
